### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by JoyceBabu** [gporais/gXipmsg#2]
It would have been really nice if there was an option to run the program in background (tray) like the Windows / Mac variants.

**Comment by gporais** [comment]
Yes indeed! But the main reason i did this app was it to run for the Motif based window manager coz i wanted to have this app on all commercial UNIX systems which i notice uses CDE as its main manager. But if you can help me do this possible please let me know anytime.

BTW, do you mind telling me how you found this project?

**Comment by JoyceBabu** [comment]
Sorry, I am a C/C++ amateur and can't help you with the coding.

gXipmsg is listed in IP Messenger website.
